export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const GET_USERDATA_REQUEST = "GET_USERDATA_REQUEST";
export const GET_USERDATA_SUCCESS = "GET_USERDATA_SUCCESS";
export const GET_USERDATA_FAIL = "GET_USERDATA_FAIL";

export const GET_USER_TESTDATA_REQUEST = "GET_USER_TESTDATA_REQUEST";
export const GET_USER_TESTDATA_SUCCESS = "GET_USER_TESTDATA_SUCCESS";
export const GET_USER_TESTDATA_FAIL = "GET_USER_TESTDATA_FAIL";